CREATE DATABASE IF NOT EXISTS salon;
USE salon;

CREATE TABLE IF NOT EXISTS clientes(id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
nombres VARCHAR(100) NOT NULL, apellidos VARCHAR(100) NOT NULL,
telefono VARCHAR(15) NOT NULL, direccion VARCHAR(255) NOT NULL,
correo_electronico VARCHAR(64) NOT NULL, password VARCHAR(100) NOT NULL,
tipo INT NOT NULL);

CREATE TABLE IF NOT EXISTS eventos(id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
title VARCHAR(45) NOT NULL, descripcion VARCHAR(45) NOT NULL,
start DATETIME NOT NULL, color VARCHAR(255) NOT NULL,
textColor VARCHAR(255) NOT NULL, id_cliente INT NOT NULL,
FOREIGN KEY(id_cliente) REFERENCES clientes(id) ON DELETE CASCADE ON UPDATE CASCADE);

INSERT INTO clientes VALUES(1,'admin','admin','019001343','conocido','admin@admin.com',sha1('admin'),1);
